version: 1.0.{build}

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master
  - /^backport\/v.*/

skip_tags: true

# TODO add ivy/coursier artifact cache
cache:
  - .targets
  - '%localappdata%\coursier'
  - '%HOMEPATH%\.sbt'
  - '%HOMEPATH%\.ivy2'
  - '%HOMEPATH%\.coursier'

environment:
  JAVA_HOME: 'C:\Program Files\Java\jdk1.8.0'
  PATH: '%JAVA_HOME%\bin;%PATH%'

# TODO remove target cache here
# before_build:
  # - cmd:

build_script:
  - cmd: .\sbt ++"2.11.8" test:compile

test_script:
  - cmd: 'echo mimir = "%localappdata%\precog" > it\testing.conf'
  - cmd: '.\sbt ++"2.11.8" it/sideEffectTestFSConfig "testOnly -- xonly" "exclusive:testOnly -- xonly"'
