version: '2'
services:
  quasar_mongodb_3_4:
    container_name: quasar_mongodb_3_4
    image: mongo:3.4.3
    command: ["mongod", "--smallfiles", "--storageEngine", "ephemeralForTest"]
    ports:
      - "27022:27017"

  quasar_mongodb_3_4_13:
    container_name: quasar_mongodb_3_4_13
    image: mongo:3.4.13
    command: ["mongod", "--smallfiles", "--storageEngine", "ephemeralForTest"]
    ports:
      - "27023:27017"

  quasar_mongodb_3_6:
    container_name: quasar_mongodb_3_6
    image: mongo:3.6.3
    command: ["mongod", "--smallfiles", "--storageEngine", "ephemeralForTest"]
    ports:
      - "27024:27017"

  quasar_metastore:
    container_name: quasar_metastore
    image: postgres:9.6.5
    privileged: true
    ports:
      - "5432:5432"
